---

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile

    ports:
      - 8080:8080
    command: npm start
    volumes:
      - .:/app

volumes:
  caddy_data:
  caddy_config:
