---

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm start
    depends_on:
      - caddy

volumes:
  caddyfile:
  caddy_data:
  caddy_config:
  
