---

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NODOS_DB_HOSTNAME}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080
    command: npm start
    environment:
      NODOS_DB_TYPE: ${NODOS_DB_TYPE}
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata:
  caddy_data:
  caddy_config:
