---

services:
  db:
    container_name: nodos_db
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: nodos_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm start
    depends_on:
      - caddy
      - db

volumes:
  pgdata:
  caddyfile:
  caddy_data:
  caddy_config:
  
